#!/usr/bin/env python3
"""Join the slide partials into the deck.

Slides are written a few at a time under build/partials/ so that several
people (or agents) can work on the deck at once without editing one file.
This joins them back, in talk order, into docs/slides/index.html and
docs/slides/assets/css/slide.css.

    python3 scripts/assemble_deck.py

The head, the script tags and the chrome live in this file, so the partials
hold nothing but <section class="slide"> elements.
"""

import re
import sys
from pathlib import Path

ORDER = ["open", "ensemble", "xai", "close"]

HEAD = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Orthogonal Ensembles and Tested Explanations — ACII 2026</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="ACII 2026 talk: performer-independent body-motion emotion recognition through orthogonal-error ensembles and tested explanations.">
    <!-- An empty data URL, so a deck with no icon does not ask the server for
         one on every load and get a 404 back. -->
    <link rel="icon" href="data:,">
    <link rel="stylesheet" href="assets/fonts.css">
    <link rel="stylesheet" href="assets/css/deck.css">
    <link rel="stylesheet" href="assets/css/slide.css">
    <link rel="stylesheet" href="assets/vendor/katex/katex.min.css">
    <link rel="stylesheet" href="assets/css/site.css">
    <link rel="stylesheet" href="assets/css/print.css" media="print">
  </head>
  <body>
    <div id="deck">
"""

TAIL = """    </div>

    <script src="assets/vendor/echarts.min.js"></script>
    <script src="assets/vendor/katex/katex.min.js"></script>
{data_scripts}
    <script src="assets/js/echarts-theme.js"></script>
{chart_scripts}
    <script src="assets/js/deck.js"></script>
    <script src="assets/js/fit.js"></script>
    <script src="assets/js/fullscreen.js"></script>
    <script src="assets/js/lightbox.js"></script>
    <script src="assets/js/math.js"></script>
    <script src="assets/js/notes.js"></script>
    <script src="assets/js/site.js"></script>
  </body>
</html>
"""


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    partials = root / "build/partials"
    slides_dir = root / "docs/slides"

    missing = [n for n in ORDER if not (partials / f"{n}.html").exists()]
    if missing:
        print(f"missing partials: {', '.join(missing)}", file=sys.stderr)
        return 1

    body, css = [], []
    for name in ORDER:
        html = (partials / f"{name}.html").read_text(encoding="utf-8").strip()
        body.append(f"      <!-- {name} -->\n{html}\n")
        sheet = partials / f"{name}.css"
        if sheet.exists() and sheet.read_text(encoding="utf-8").strip():
            css.append(f"/* ---- {name} ---- */\n{sheet.read_text(encoding='utf-8').strip()}\n")

    data = sorted(p.name for p in (slides_dir / "assets/data").glob("*.js"))
    charts = sorted(p.name for p in (slides_dir / "assets/js/charts").glob("*.js"))
    tail = TAIL.format(
        data_scripts="\n".join(f'    <script src="assets/data/{n}"></script>' for n in data),
        chart_scripts="\n".join(f'    <script src="assets/js/charts/{n}"></script>' for n in charts),
    )

    (slides_dir / "index.html").write_text(HEAD + "\n".join(body) + tail, encoding="utf-8")
    (slides_dir / "assets/css/slide.css").write_text(
        "/* Per-slide layout. Generated by scripts/assemble_deck.py from\n"
        "   build/partials/*.css — edit those, not this file. */\n\n"
        + "\n".join(css),
        encoding="utf-8",
    )

    html = (slides_dir / "index.html").read_text(encoding="utf-8")
    ids = re.findall(r'<section class="slide[^"]*" id="(s-\d\d-[^"]+)"', html)
    print(f"{len(ids)} slides -> docs/slides/index.html")
    for i, sid in enumerate(ids, 1):
        want = f"s-{i:02d}-"
        flag = "" if sid.startswith(want) else f"   <- expected {want}*"
        print(f"  {i:2d}  {sid}{flag}")
    if len(set(ids)) != len(ids):
        print("duplicate slide ids", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
