#!/usr/bin/env python3
"""Turn the paper's committed artifacts into the data files the site loads.

Everything here reads from the LaTeX repository (--paper-repo) and writes
JavaScript into docs/slides/assets/data/ and JSON into docs/assets/data/.
Nothing is recomputed from raw motion capture: the source files are the same
CSV, JSON, TeX and NPZ artifacts the paper's figures were built from, so a
number on a slide and the same number in the paper come from one place.

Run after any change to those artifacts:

    python3 scripts/build_site_data.py --paper-repo ~/GITs/LaTeX/MMAC_ACII2026
"""

import argparse
import csv
import json
import re
from pathlib import Path

import numpy as np

EMOTIONS = ["anger", "contempt", "disgust", "fear", "joy", "sadness",
            "surprise", "jealousy", "shame", "guilt", "gratitude", "pride"]


def write_js(path: Path, key: str, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    path.write_text(
        "// Generated by scripts/build_site_data.py — do not edit by hand.\n"
        "window.DeckData = window.DeckData || {};\n"
        f"window.DeckData[{json.dumps(key)}] = {body};\n",
        encoding="utf-8",
    )
    print(f"  {path.relative_to(path.parents[4])}  ({path.stat().st_size:,} B)")


def write_json(path: Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
                    encoding="utf-8")
    print(f"  {path.relative_to(path.parents[3])}  ({path.stat().st_size:,} B)")


def build_lift_path(paper: Path):
    stats = json.loads((paper / "MMAC_ACII2026/paper/figures/fig02_lift_path_stats.json").read_text())
    rec = json.loads((paper / "MMAC_ACII2026/paper/reconcile_f1.json").read_text())
    order = ["STGCN++ baseline", "best single (Region-Aware)", "7-way ensemble", "11-way logit-mean"]
    labels = ["STGCN++\nreproduced", "Best single\n(Region-Aware)", "7-way\nensemble", "11-way logit-mean\n(submitted)"]
    per_fold = {
        "STGCN++ baseline": rec["exp001_baseline"]["per_fold_macro_f1"],
        "7-way ensemble": rec["grid"]["7way__logit_mean"]["per_fold_macro_f1"],
        "11-way logit-mean": rec["grid"]["11way__logit_mean"]["per_fold_macro_f1"],
    }
    stages = []
    for name, label in zip(order, labels):
        s = stats["stages"][name]
        stages.append({
            "key": name,
            "label": label,
            "mean": round(s["perfold_mean_pct"], 2),
            "sd": round(s["perfold_sd_pct"], 2),
            "pooled": round(s["pooled_pct"], 2),
            "ci": [round(s["boot95_ci_pct"][0], 2), round(s["boot95_ci_pct"][1], 2)],
            "perFold": [round(v * 100, 2) for v in per_fold.get(name, [])],
        })
    return {
        "stages": stages,
        "chance": 8.3,
        "gainPp": round(stages[-1]["mean"] - stages[0]["mean"], 2),
        "gainRelPct": round(100 * (stages[-1]["mean"] - stages[0]["mean"]) / stages[0]["mean"]),
        "nOof": rec["n_oof"],
    }


def build_member_corr(paper: Path):
    rows = (paper / "MMAC_ACII2026/paper/figures/fig04_member_corr_values.csv").read_text().splitlines()
    rows = [r for r in rows if not r.startswith('"#')]
    reader = list(csv.reader(rows))
    members = reader[0][1:]
    matrix = [[float(v) for v in r[1:]] for r in reader[1:]]
    off = [matrix[i][j] for i in range(len(members)) for j in range(len(members)) if i != j]
    family = {
        "STGCN++": "graph", "CTR-GCN": "graph", "ProtoGCN": "graph", "Region-Aware": "graph",
        "SkateFormer": "attention", "Conv1D+Tr": "hybrid", "KP-MLP": "hybrid",
        "MotionBERT": "external", "C3D-stats": "external",
        "MAMP-NTU60": "external", "MAMP-NTU120": "external",
    }
    return {
        "members": members,
        "family": [family[m] for m in members],
        "matrix": matrix,
        "min": round(min(off), 4),
        "max": round(max(off), 4),
        "note": "Pearson correlation of per-sample error indicators (phi), out-of-fold n=7,992.",
    }


def build_loo(paper: Path):
    tex = (paper / "tables/table_member_loo.tex").read_text()
    rows = []
    for line in tex.splitlines():
        m = re.match(r"^(.+?) & (.+?) & \$(-[\d.]+)\$ \\\\", line.strip())
        if m:
            rows.append({"member": m.group(1).strip(),
                         "family": m.group(2).strip(),
                         "delta": float(m.group(3))})
    block = [r for r in rows if r["member"].startswith("All frozen")]
    members = [r for r in rows if not r["member"].startswith("All frozen")]
    return {
        "members": members,
        "block": block[0] if block else None,
        "base": 36.94,
        "note": "Change in pooled out-of-fold Macro-F1 when one member leaves the logit mean.",
    }


def build_lma(paper: Path):
    d = paper / "MMAC_ACII2026/experiments/exp091_ensemble_lma_faithfulness"
    single = json.loads((d / "results_single_model.json").read_text())
    ens = json.loads((d / "results_11way.json").read_text())
    per = [{
        "emotion": e,
        "member": round(single["per_emotion_spearman"][e], 3),
        "ensemble": round(ens["per_emotion_spearman_ensemble"][e], 3),
        "kinematics": round(ens["per_emotion_spearman_exp079"][e], 3),
    } for e in EMOTIONS]
    return {
        "perEmotion": per,
        "headline": {
            "memberRho": 0.500, "kinematicsRho": 0.033,
            "memberCi": [0.150, 0.733],
            "ensembleRho": 0.517, "ensembleCi": [0.333, 0.700],
            "ensembleP": 0.001,
        },
        "note": "Region-level Spearman correlation between saliency and rule-based Laban attributes.",
    }


def build_saliency(paper: Path):
    z = np.load(paper / "MMAC_ACII2026/experiments/exp078_temporal_spatial_saliency/results.npz",
                allow_pickle=True)
    temporal = np.asarray(z["temporal_sal"], dtype=float)   # (12, 64)
    spatial = np.asarray(z["spatial_sal"], dtype=float)     # (12, 25)
    joints = [str(j) for j in z["joint_names"]]
    labels = [str(e) for e in z["emotion_labels"]]

    def norm_rows(a):
        s = a.sum(axis=1, keepdims=True)
        return np.divide(a, s, out=np.zeros_like(a), where=s > 0)

    tp = norm_rows(temporal)
    ent = -(tp * np.log(np.clip(tp, 1e-12, None))).sum(axis=1) / np.log(temporal.shape[1])
    sp = norm_rows(spatial)
    return {
        "emotions": labels,
        "joints": joints,
        "temporal": [[round(v, 6) for v in row] for row in tp],
        "spatial": [[round(v, 6) for v in row] for row in sp],
        "temporalEntropyPct": [round(float(v) * 100, 2) for v in ent],
        "temporalEntropyMeanPct": round(float(ent.mean()) * 100, 2),
        "uniform": round(1.0 / temporal.shape[1], 6),
        "nFrames": int(temporal.shape[1]),
        "note": "Class-mean saliency, row-normalised. Temporal is near-uniform; spatial is head-dominant.",
    }


def read_csv_table(path: Path):
    with path.open(encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader)
        return {"header": header, "rows": [r for r in reader]}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--paper-repo", default="~/GITs/LaTeX/MMAC_ACII2026")
    ap.add_argument("--site", default=str(Path(__file__).resolve().parents[1]))
    args = ap.parse_args()
    paper = Path(args.paper_repo).expanduser().resolve()
    site = Path(args.site).resolve()
    deck = site / "docs/slides/assets/data"
    page = site / "docs/assets/data"

    tables = paper / "MMAC_ACII2026/paper/tables"
    payloads = {
        "liftpath": build_lift_path(paper),
        "membercorr": build_member_corr(paper),
        "loo": build_loo(paper),
        "lma": build_lma(paper),
        "saliency": build_saliency(paper),
        "results": read_csv_table(tables / "table1_main_results.csv"),
        "negatives": read_csv_table(tables / "table2_negatives.csv"),
        "explainability": read_csv_table(tables / "table3_explainability.csv"),
    }

    print("deck data:")
    for key, payload in payloads.items():
        write_js(deck / f"{key}.js", key, payload)
    print("page data:")
    for key, payload in payloads.items():
        write_json(page / f"{key}.json", payload)

    sal = payloads["saliency"]
    print(f"\ncheck  temporal entropy, class mean = {sal['temporalEntropyMeanPct']}% of log T "
          f"(paper reports 99.5%)")
    lift = payloads["liftpath"]
    print(f"check  headline gain = +{lift['gainPp']} pp (+{lift['gainRelPct']}%), "
          f"paper reports +11.07 pp / +43%")
    mc = payloads["membercorr"]
    print(f"check  member error correlations in [{mc['min']}, {mc['max']}], "
          f"paper reports [0.15, 0.43]")


if __name__ == "__main__":
    main()
